### ISSUE TITLE
wow, what is this?

### ISSUE THREAD

**Issue by nitinthewiz** [riaf/fbjssdk#1]
I'd love to know what you're trying to do here. Interesting thing that you're pulling all the JS SDK Code from the FB site, but why?

**Comment by riaf** [comment]
This repository is because there is that FBSDK is show a sudden strange behavior, what it is necessary to know whether caused by change. (so, this is the diff.)

**Comment by nitinthewiz** [comment]
Interesting! Thanks for the tip... I'll look in on this repo every once in a while :)
